name: maid
description: A cross-platform Flutter app for chatting with AI.
publish_to: 'none'

version: 2.0.0+1885

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  flutter_colorpicker: ^1.1.0
  file_picker: 8.1.7
  tree_structs: ^1.0.5
  lcpp: ^0.1.5
  ollama_dart: ^0.2.2+1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - maid.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "maid.png"
  windows:
    generate: true
    image_path: "maid.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "maid.png"