stages:
  - build

build-apk:
  stage: build
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
  tags:
    - saas-linux-medium-amd64
  only:
    - main
  variables:
    repo: /home/runner/work/maid
    ANDROID_HOME: /opt/android-sdk
    ANDROID_SDK_ROOT: ${ANDROID_HOME}
  before_script:
    - rm -rf /home/vagrant/build
    - rm -rf /opt/android-sdk/ndk
    - apt-get update 
    - apt-get install -y openjdk-17-jdk-headless  # Install OpenJDK 17
    - rm -rf $ANDROID_HOME/tools  # TODO remove once sdkmanager can upgrade installed packages
    - sdkmanager "tools" "platform-tools" "build-tools;31.0.0"
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - export PUB_CACHE=$(pwd)/.pub-cache
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 

    # Build and configure Flutter from submodule
    - ./packages/flutter/bin/flutter config --no-analytics
    - ./packages/flutter/bin/flutter packages pub get

    # Decrypt the keystore
    - echo "$KEYSTORE" | base64 --decode > ./android/app/key.jks
    - |
      echo "storeFile=key.jks" > ./android/key.properties
      echo "storePassword=$STORE_PASSWORD" >> ./android/key.properties
      echo "releasePassword=$KEY_PASSWORD" >> ./android/key.properties
      echo "releaseAlias=$KEY_ALIAS" >> ./android/key.properties

    # Build the APK (now from the project root)
    - ./packages/flutter/bin/flutter build apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
